raw_cloud_colorizer:
  ros__parameters:
    input_cloud_topic: /ouster/points
    input_image_topic: /basler_front/image_raw/compressed
    camera_info_topic: /basler_front/camera_info
    output_cloud_topic: /colorizer/raw/colored_cloud
    output_frame_id: ""
    publish_only_colored_points: true
    transform_source: config
    camera_frame_id: pylon_camera
    lidar_frame_id: os1/os_lidar
    transform_lookup_timeout_sec: 0.1
    camera_to_lidar_matrix: [
      0.019, 0.0, -1.0, -0.058,
      -1.0, 0.0, -0.019, -0.001,
      0.0, 1.0, 0.0, -0.145,
      0.0, 0.0, 0.0, 1.0
    ]